apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs
  namespace: openebs
spec:
  chart:
    spec:
      chart: openebs
      version: "3.8"
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: openebs
  values:
    localprovisioner:
      deviceClass:
        enabled: false
      hostpathClass:
        enabled: false
