apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflare-zero-trust-operator
  namespace: zero-trust-system
spec:
  chart:
    spec:
      chart: cloudflare-zero-trust-operator
      version: 0.3.1
      sourceRef:
        kind: HelmRepository
        name: zelic-io
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: cloudflare-zero-trust-operator
  values:
    secretRef: cloudflare-creds
