apiVersion: v1
metadata:
    name: cloudflare-creds
    namespace: zero-trust-system
kind: Secret
type: Opaque
stringData:
    CLOUDFLARE_ACCOUNT_ID: ENC[AES256_GCM,data:y7/zpo9L7a5CEBHLmk5mV738NHg/DT1NeMMblMCFtm4=,iv:Bw8bnnYuxhbh9IC78+Z3mDojxwf0ZKe7BPGS57+BC0c=,tag:Koo38s9MOdPP0Fdhh7rbPg==,type:str]
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:cxbeH5tOVAfvmQDfIVgy7dG+reclgemfliPRpPvDs49SU9Cwp1U/nA==,iv:v43GdYS3I08NNPjGyAGaoa0ZNcCaAfOGYtXMKhwvFSk=,tag:JSA8+S0X7gPE768oUgX+vA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1eukrrh4fnxqmy6mz4qln64wtyetpk5ckz0aqj7gyr67v4cwtkgqs0xx7pv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6VkR2OEdhMUE2K1NWVHpK
            b3FxMTZRRCs2SWhLOG1TMGpyeWpoWVA4K1QwCkk4Zlo0QnBzK2pkbGNmZWRKazhQ
            QUl5cXI2OXhPTlN0QnBteForSE9pOEEKLS0tIGY3Qzd3UTVZVVN6SjRFMHFpc0hX
            bjd5SWEzc1gzT3RNckpPV2ZJTVE5WkUKCMC7WgAGRSx81cwFK9+wDxfcWJ/zM6uz
            IXIperITq01cWrZnri7coEqF4HWI+ZQAAm1FG3dW2LIZ0ETu0spjnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-03T14:19:24Z"
    mac: ENC[AES256_GCM,data:8TH0JY0COPeH/ginbiGpT+3q3a9jdxMeQ9r+F0YDncraQHEW7DorbyICvxh/ce3UDyszpIp+kUOVGq2dRk5Nrol9XifAgfRjMBMBhzMvgT9Hk955e1k769GWRVWUf8+Xi+rGRVa11kJDVeVJlwfRVghKAIvhtRjctrgIlyPRybA=,iv:jrmJouVVzJuBrv/yaF7e/+pzaz1fMHMRwuCUy4DWnlg=,tag:xgOk6SnlTfOrA8VeSowYoQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
